### ISSUE TITLE
the url for the intent schema and slots are not available 

### ISSUE THREAD

**Issue by AlfredSharon** [carsonip/alexa-whatsapp#1]
HI 
Please can you update the url for the intent schema, slot types etc. 
or better still just update it as a file under the alexa skill folder 
Pleaseee.

**Comment by carsonip** [comment]
This project is not actively maintained anymore. Feel free to submit a PR.

**Comment by AlfredSharon** [comment]
Hi please whats the pr i am new to this and i need your sample code to create something
