### ISSUE TITLE
Last Message please

### ISSUE THREAD

**Issue by AlfredSharon** [carsonip/alexa-whatsapp#3]
wow already chose this for my Final Year project now i'm stuck.
am conversant with all those i meant new to javascript programming though still learning. thanks for pointing out the python server part.
i'd stop disturbing please just drop down all the tools needed. is there anything else apart from Lambda, Alexa, and Python Server,
i have gone through a process and my skill can only say welcome to talking whatsapp
A brief process please and i will take it from there. Thanks

**Comment by carsonip** [comment]
1. Try to start a Heroku instance and it will read the [Procfile](https://devcenter.heroku.com/articles/procfile) and spin up the Python server in the root of this repository.
2. Create a Amazon lambda function and upload the js file inside alexa-skill directory in the repo.
3. Create the Alexa skill, make up your own intents and utterances, connect to the lambda function.
4. Make changes to code and configurations (e.g. the heroku url in the lambda function, the contacts mapping in Python code, etc.)

Good luck.
